using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Cinder14.EchoSign.OAuth
{
    public class TokenInfo
    {
        /// <summary>
        /// The value will always be "Bearer".
        /// </summary>
        public virtual string token_type { get; set; }
        /// <summary>
        /// Access Token, which can be used as an API_KEY in Adobe Document Cloud's APIs
        /// </summary>
        public virtual string access_token { get; set; }
       
        /// <summary>
        /// The lifetime in seconds of the Access Token.
        /// </summary>
        public virtual int expires_in { get; set; }

        /// <summary>
        /// The raw response this class was generated from
        /// </summary>
        public virtual string raw_response { get; set; }

        /// <summary>
        /// Computed only when generated by EchoSignOAuth methods
        /// </summary>
        public DateTime? expiration_date { get; set; }
    }
}
